version: 2.1
jobs:
  hello:
    docker:
      - image: fabiogallotti/tutorial_ci
    steps:
      - checkout
      - run:
          name: Hello World
          command: echo "Hello World"
workflows:
  hello:
    jobs:
      - hello